services:
  postgres:
    image: postgres:17beta1-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=yuji
      - POSTGRES_PASSWORD=S3cret